export const FETCH_TRANSLATIONS = '@app/FETCH_TRANSLATIONS';
export const FETCH_TRANSLATIONS_SUCCESS = '@app/FETCH_TRANSLATIONS_SUCCESS';
export const FETCH_TRANSLATIONS_FAILURE = '@app/FETCH_TRANSLATIONS_FAILURE';

export const START_LOADING = '@@app/START_LOADING';
export const STOP_LOADING = '@@app/STOP_LOADING';

export const SHOW_MOBILE_MENU = '@app/SHOW_MOBILE_MENU';
export const HIDE_MOBILE_MENU = '@app/HIDE_MOBILE_MENU';
