enum TypeKeys {
    FETCH_TRANSLATIONS = '@app/FETCH_TRANSLATIONS',
    FETCH_TRANSLATIONS_SUCCESS = '@app/FETCH_TRANSLATIONS_SUCCESS',
    FETCH_TRANSLATIONS_FAILURE = '@app/FETCH_TRANSLATIONS_FAILURE',
    START_LOADING = '@@app/START_LOADING',
    STOP_LOADING = '@@app/STOP_LOADING',
    SHOW_MOBILE_MENU = '@app/SHOW_MOBILE_MENU',
    HIDE_MOBILE_MENU = '@app/HIDE_MOBILE_MENU',
}

export default TypeKeys;
