enum TypeKeys {
    AUTHENTICATE = '@@user/AUTHENTICATE',
    AUTHENTICATE_SUCCESS = '@@user/AUTHENTICATE_SUCCESS',
    AUTHENTICATE_FAILURE = '@@user/AUTHENTICATE_FAILURE',
    LOGOUT = '@@user/LOGOUT',
    LOGOUT_FINISHED = '@@user/LOGOUT_FINISHED',
    FETCH_USER_DATA = '@@user/FETCH_USER_DATA',
    FETCH_USER_DATA_SUCCESS = '@@user/FETCH_USER_DATA_SUCCESS',
    FETCH_USER_DATA_FAILURE = '@@user/FETCH_USER_DATA_FAILURE',
    FETCH_USER_DATA_NOT_LOGGED_IN = '@@user/FETCH_USER_DATA_NOT_LOGGED_IN',
    FETCH_USERS = '@@user/FETCH_USERS',
    FETCH_USERS_SUCCESS = '@@user/FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE = '@@user/FETCH_USERS_FAILURE',
}

export default TypeKeys;
